### ISSUE TITLE
Lesson learned on IE compatibility issues

### ISSUE THREAD

**Issue by genkio** [genkio/blog#115]
When you set an inline element to `display: inline-block`, you'll need to specify a fixed height to that element.
_without the height specified (IE 9)_
![image](https://cloud.githubusercontent.com/assets/5327840/19374912/68cabcb8-920a-11e6-9923-2b436d69f5a4.png)
_this is how it suppose to look_
![image](https://cloud.githubusercontent.com/assets/5327840/19375301/98573c24-920d-11e6-94d8-e67c219c7d69.png)
### The fix

``` css
a {
  .inline;
  .font-bold;
  .cursor;
  height: 30px; // the fix
  margin-top: 15px;
  padding: 5px 10px;
}
```

So, you try to line up say 4 elements in a row, and in order to set them apart from each other, you set a right margin to each element, however, in IE (9), the 4th element will show up in the second row.
![image](https://cloud.githubusercontent.com/assets/5327840/19374837/d150e704-9209-11e6-955b-9a676dd4e96a.png)
### The fix

``` css
.parent-class {
  &:nth-child(4n) {
    .some-elem {
      margin-right: 0;
    }
  }
}
```
