### ISSUE TITLE
Boost up your CSS productivity instantly with these 3 SCSS basic syntax

### ISSUE THREAD

**Issue by genkio** [genkio/blog#26]
Variables $

``` scss
$primary-color: #00BCD4;

header {
    background-color: $primary-color;
}
```

Nested Rules

``` scss
.hero {
    padding: 80px;
    .btn {
        width: 100px;
        height: 40px;
        background-color: $accent-color;
    }
    &:hover {
        background-color: lighten($accent-color, 10%);
        cursor: pointer;
    }
}
```

@-Rules

``` scss
/* sections.scss */
header {
    background-color: $primary-color;
    height: 70px;
}
```

``` scss
/* main.scss */
@import "sections"
```

Lastly, build with [gulp](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md) and [gulp-sass](https://www.npmjs.com/package/gulp-sass)

``` javascript
// gulpfile.js

var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('sass', function(){
  gulp.src('src/main.scss')
      .pipe(sass())
      .pipe(gulp.dest('dist/'));
});

gulp.task('copy-assets', function(){
  gulp.src('src/*.html')
      .pipe(gulp.dest('dist/'));
});

gulp.task('default', ['sass', 'copy-assets']);
```

For more information on [SCSS](http://www.sass.hk/sass-course.html)
