### ISSUE TITLE
Getting started with CSS animation

### ISSUE THREAD

**Issue by genkio** [genkio/blog#98]
### transition
- syntax

``` css
.element {
    transition: [property] [duration] [ease] [delay];
}
```
- example

``` css
.element {
    transition: opacity 300ms ease-in-out 1s;
}
```
- performant animatable properties
  - position
  - scale
  - rotation
  - opacity
- [in action](http://j1wu.github.io/frontend-playground/sandbox/css/animation/transition-starter/)
### keyframes
- syntax

``` css
@keyframes [name] {
    from { // same as 0%
        [styles];
    }
    to {   // same as 100%
        [styles];
    }
}
```
- example

``` css
@keyframes myframes {
    from {
        height: 200px;
    }
    to {
        height: 400px;
    }
}
```
- syntax for animation property

``` css
.element {
    animation: [name] [duration] [timing-function] [delay] [iteration-count] [direction] [fill-mode] [play-state];
}
```
- example for animation property

``` css
.element {
    animation: myframes 2s ease-in-out 0s infinite normal forwards paused;
}
```
- [in action](http://j1wu.github.io/frontend-playground/sandbox/css/animation/keyframes-starter/)
